### ISSUE TITLE
no m3u8 cause sub process crash

### ISSUE THREAD

**Issue by zhangping** [i4tv/gstreamill#102]
```
Thread 31 "queue2:src" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7efd99cf4700 (LWP 4385)]
0x0000000000411bf1 in new_sample_callback (elt=<optimized out>, user_data=0x13275c0) at source.c:766
766                 if ((stream->state->last_heartbeat % stream->segment_duration) < 100000000/* 100ms */) {
(gdb) bt
#0  0x0000000000411bf1 in new_sample_callback (elt=<optimized out>, user_data=0x13275c0) at source.c:766
#1  0x00007efdc688516a in gst_app_sink_render_common (psink=0x149cd90, data=0x7efd8c01b8b0, is_list=<optimized out>)
    at gstappsink.c:883
#2  0x00007efdc664366e in gst_base_sink_chain_unlocked (basesink=basesink@entry=0x149cd90, obj=obj@entry=0x7efd8c01b8b0,
    is_list=is_list@entry=0, pad=<optimized out>) at gstbasesink.c:3550
#3  0x00007efdc66447e0 in gst_base_sink_chain_main (basesink=0x149cd90, pad=<optimized out>, obj=0x7efd8c01b8b0, is_list=0)
    at gstbasesink.c:3676
#4  0x00007efdc635518f in gst_pad_chain_data_unchecked (data=0x7efd8c01b8b0, type=4112, pad=0x14636c0) at gstpad.c:4205
#5  gst_pad_push_data (pad=pad@entry=0x1463480, type=type@entry=4112, data=data@entry=0x7efd8c01b8b0) at gstpad.c:4457
#6  0x00007efdc635d273 in gst_pad_push (pad=0x1463480, buffer=buffer@entry=0x7efd8c01b8b0) at gstpad.c:4576
#7  0x00007efda2e87a78 in gst_queue_push_one (queue=0x1468670) at gstqueue.c:1365
#8  gst_queue_loop (pad=<optimized out>) at gstqueue.c:1517
#9  0x00007efdc6388b71 in gst_task_func (task=0x152a830) at gsttask.c:335
#10 0x00007efdc581954e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007efdc5818bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007efdc538a6ba in start_thread (arg=0x7efd99cf4700) at pthread_create.c:333
#13 0x00007efdc49bd3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by zhangping** [comment]
rsolved
