### ISSUE TITLE
启动时挂掉

### ISSUE THREAD

**Issue by zhangping** [i4tv/gstreamill#108]
启动时挂掉
```
#0  __GI__IO_setvbuf (fp=0x0, buf=buf@entry=0x0, mode=mode@entry=1, size=size@entry=0) at iosetvbuf.c:38
38      iosetvbuf.c: No such file or directory.
(gdb) bt
#0  __GI__IO_setvbuf (fp=0x0, buf=buf@entry=0x0, mode=mode@entry=1, size=size@entry=0) at iosetvbuf.c:38
#1  0x00000000004182cd in log_set_log_handler (log=log@entry=0x165bc80) at log.c:203
#2  0x0000000000408fa1 in main (argc=1, argv=0x7fffb4d375a8) at main.c:547
```

**Comment by Fairy1018** [comment]
你好，最后是怎么解决的，我在虚拟机上使用setvbuf也出现了这个问题

**Comment by zhangping** [comment]
@Fairy1018  https://github.com/i4tv/gstreamill/commit/1d9c793cbc845ce364c4bde16cc8d37013c54d0f
