### ISSUE TITLE
运行时挂掉

### ISSUE THREAD

**Issue by zhangping** [i4tv/gstreamill#110]
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `gstreamill -d -m 10.10.46.173:20118 -a 10.10.46.173:20119'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  msg_thread (data=0x223f100) at gstreamill.c:987
987                 sem_post (encoder_output->semaphore);
[Current thread is 1 (Thread 0x7f8dd95ad700 (LWP 22))]
(gdb) bt
#0  msg_thread (data=0x223f100) at gstreamill.c:987
#1  0x00007f8dded78bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f8dde8ea6ba in start_thread (arg=0x7f8dd95ad700) at pthread_create.c:333
#3  0x00007f8dddf2841d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by zhangping** [comment]
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `gstreamill -d -m 10.10.46.158:20118 -a 10.10.46.158:20119'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __new_sem_post (sem=0xd514e7559d13cd74) at sem_post.c:36
36      sem_post.c: No such file or directory.
[Current thread is 1 (Thread 0x7f8a5e304700 (LWP 22))]
(gdb) bt
#0  __new_sem_post (sem=0xd514e7559d13cd74) at sem_post.c:36
#1  0x000000000040d8c9 in msg_thread (data=0xe9c100) at gstreamill.c:987
#2  0x00007f8a63acfbb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f8a636416ba in start_thread (arg=0x7f8a5e304700) at pthread_create.c:333
#4  0x00007f8a62c7f41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by zhangping** [comment]
duplicate
