### ISSUE TITLE
播放请求直接被拒绝

### ISSUE THREAD

**Issue by zhangping** [i4tv/gstreamill#76]
现象是播放请求直接被拒绝：
```
Dec 28 13:56:23.470045 ERROR  gstreamill httpserver.c:490: event queue empty
Dec 28 13:56:23.471203 ERROR  gstreamill httpserver.c:490: event queue empty
Dec 28 13:56:23.632000 ERROR  gstreamill httpserver.c:490: event queue empty
Dec 28 13:56:23.656604 ERROR  gstreamill httpserver.c:490: event queue empty
Dec 28 13:56:23.680561 ERROR  gstreamill httpserver.c:490: event queue empty
Dec 28 13:56:23.768317 ERROR  gstreamill httpserver.c:490: event queue empty
Dec 28 13:56:23.991428 ERROR  gstreamill httpserver.c:490: event queue empty
```
原因是极有可能是发送了如下回看请求：
```
(gdb) bt
#0  0x00007fec126b81ff in g_queue_peek_nth_link () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007fec126b85fe in g_queue_peek_nth () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00000000004209a5 in m3u8playlist_target_duration (playlist=<optimized out>) at m3u8playlist.c:85
#3  m3u8playlist_render (playlist=0x7fea1939b920) at m3u8playlist.c:106
#4  m3u8playlist_add_entry (playlist=playlist@entry=0x7fea1939b920,
    url=url@entry=0x7feb71dc024b "2015122401/1791611603_189101_5020000000.ts", duration=5.02000026e+09) at m3u8playlist.c:139
#5  0x000000000042127e in m3u8playlist_callback_get_playlist (path=0x7febdc001100 "/var/lib/gstreamill/dvr/00000110240011_1/1",
    start=start@entry=0x7feb728075b0 "20110101193100", end=end@entry=0x7febc15ddad0 "20151226201900") at m3u8playlist.c:311
#6  0x00000000004180cd in get_m3u8playlist (encoder_output=0x7febdc00aee0, encoder_output=0x7febdc00aee0,
    request_data=0x7fec0dab6010) at httpstreaming.c:577
#7  http_request_process (request_data=0x7fec0dab6010, httpstreaming=0x10688d0) at httpstreaming.c:631
#8  httpstreaming_dispatcher (data=0x7fec0dab6010, user_data=0x10688d0) at httpstreaming.c:773
#9  0x000000000040e325 in invoke_user_callback (http_server=0x10a4200, request_data_pointer=0x10a4308) at httpserver.c:807
#10 0x00007fec126cd88c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fec126ccf05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007fec12241182 in start_thread (arg=0x7febfe007700) at pthread_create.c:312
#13 0x00007fec1189947d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by zhangping** [comment]
应该重写代码，生成回看m3u8，一方面由于现在生成m3u8的方法当列表很大的时候，会在调用g_queue_peek_nth卡住，当连续过多调用被卡住的时候，就会拒绝访问，另一方面，效率也很低。
